### PR TITLE
[#2417] project_update API POST fails when photo is None

### LINKED ISSUE #2417: akvo.rest.fields in from_native AttributeError: 'NoneType' object has no attribute 'name'
http://sentry.support.akvo-ops.org/rsr/live/group/1017/

Bug introduced in 1aa60508350d4477c1f0964db7f3c124d9d1bc01

### PR DESCRIPTION
**Pull request by punchagan**
- [x] Test plan | Unit test | Integration test
- [x] Copyright header
- [x] Code formatting
- [x] Documentation
- [x] Change log entry

This bug was introduced in 1aa60508350d4477c1f0964db7f3c124d9d1bc01

Any API POST where 'photo' field is None would fail, but I don't yet know what exact user action triggered this report: http://sentry.support.akvo-ops.org/rsr/live/group/1017/

Closes #2417

### CODE REVIEW

**Comment by punchagan** [comment]
# Test plan

- Pick any project with a photo for the project
- Go to Section 1 of the project editor
- Try to delete the photo, and it should work.
