### ISSUE TITLE
akvo.rest.fields in from_native AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2417]
http://sentry.support.akvo-ops.org/rsr/live/group/1017/

Bug introduced in 1aa60508350d4477c1f0964db7f3c124d9d1bc01
